@startuml
!include ./Extension/TransformExtensions.puml
!include ./Extension/EnumExtensions.puml
!include ./Extension/GameObjectExtensions.puml
!include ./Extension/ComponentExtensions.puml
!include ./Extension/DictionaryExtensions.puml
!include ./Extension/AnimationExtensions.puml
!include ./Widget/NonRepeatRandom.puml
!include ./Widget/TransformRotate.puml
!include ./Property/EnumFlagAttribute.puml
!include ./Property/OptionalValue.puml
!include ./Property/RangeValue.puml
!include ./DataStructure/SerializableDictionary.puml
!include ./DataStructure/SerializableHashSet.puml
!include ./Global/InstanceContainer.puml
!include ./Debug/ModuleDebugData.puml
!include ./Debug/DebugSettings.puml
!include ./Utility/EnumUtil.puml
!include ./Utility/AnimationUtil.puml
!include ./Utility/WaitUtil.puml
!include ./Utility/ObjectUtil.puml
!include ./Utility/TransformUtil.puml
!include ./Utility/DictionaryUtil.puml
!include ./Utility/ListUtil.puml
!include ./Utility/RayUtil.puml
!include ./Utility/MathUtil.puml
!include ./Singleton/Interface/IResourceSingletonProvider.puml
!include ./Singleton/Interface/ISingletonCreateHandler.puml
!include ./Singleton/Interface/ISingletonProvider.puml
!include ./Singleton/Interface/IMonoSingletonDestroyHandler.puml
!include ./Singleton/Interface/IMonoSingletonAwakeHandler.puml
!include ./Singleton/Provider/ScriptableResourceSingletonProvider.puml
!include ./Singleton/Provider/ResourceSingletonProvider.puml
!include ./Singleton/Provider/GeneralSingletonProvider.puml
!include ./Singleton/Provider/ResourceInstantiateSingletonProvider.puml
!include ./Singleton/Provider/ResourceComponentSingletonProvider.puml
!include ./Singleton/Provider/ComponentSingletonProvider.puml
!include ./Singleton/Provider/ScriptableSingletonProvider.puml
!include ./Singleton/Implement/MonoSingleton.puml
!include ./Singleton/Implement/MonoResourceDefaultSingleton.puml
!include ./Singleton/Implement/GeneralSingleton.puml
!include ./Singleton/Implement/ScriptableResourceDefaultSingleton.puml
!include ./Singleton/Implement/ScriptableSingleton.puml
!include ./Singleton/Implement/MonoDefaultSingleton.puml
!include ./Singleton/Implement/ScriptableDefaultSingleton.puml
!include ./Singleton/Implement/GeneralDefaultSingleton.puml
!include ./Singleton/Utility/SingletonUtil.puml
@enduml
